### ISSUE TITLE
Standardize CAN ID/message allocation and usage.

### ISSUE THREAD

**Issue by AdamBusch** [PurdueElectricRacing/Wireless-Telemetry-Server#12]
We are only using the google form for managing CAN IDs and message frames. While this google doc and be updated, it does not necessarily mean that any code reflects this in the main module.

We should create some scripts that will generate C header files with constant #define for each message and data bit. These files can be easily re-generated to reflect any updates on the google sheet or CSV file in this repo.

Example snippet of C header file:

'CAN_CONSTANTS.h'
...
#define ACCEL_CAN_ID 0x7a1
#define ACCEL_TYPE_START_BYTE 0
#define ACCEL_TYPE_END_BYTE 1
#define ACCEL_DATA_START_BYTE 2
#define ACCEL_DATA_END_BYTE 5
#define ACCEL_TIME_START_BYTE 6
#define ACCEL_TIME_END_BYTE 7
...

**Comment by jacklecroy** [comment]
So should we make the CSV file pull from the Google sheet? It'll be easiest for the script to pull from the CSV file, but should that file be the primary source, or the sheet?

**Comment by jacklecroy** [comment]
Alright, I've got a working script that will do this, except the names aren't quite standardized. By this, I mean "TYPE" isn't always after the last underscore. For example:
- in `TIRE_ROD_RL` the "TYPE" is "RL"
- but in `STEERING_SHAFT_TORSION` the "TYPE" is "SHAFT_TORSION" when it should be something like "SHAFTTORSION"

I'll hold off on committing it til we get the PRs merged.

**Comment by AdamBusch** [comment]
We currently have 3 helper files for managing the CAN IDs and they are scattered through the project. We need to refactor how we manage these files by combining these scripts and placing them in a standalone directory.

**Comment by jacklecroy** [comment]
Update sensordict and generate header file can be combined, but I'm not confident in that until the spreadsheet is 100% correct
